### ISSUE TITLE
"Generate NFTs" Button is Missing on UI

### ISSUE THREAD

**Issue by ethangale25** [torrinworx/Blend_My_NFTs#89] opened 2022-04-13 20:06 UTC
![image](https://user-images.githubusercontent.com/30662677/163260946-66332d7d-07c1-422d-9126-bcfe29f0b607.png)
The "Generate NFTs" button is missing on the user interface.
I have verified that I am using the most recent version of BMNFTs and have tried Blender 3.1.2 as well as Blender 3.0.0
Note that Version 2.0.0 of BMNFTs DOES show the button for this particular .blend file.

Also If I start a new .blend file, the "Generate NFTs" button DOES show.

**Comment by torrinworx** [comment] 2022-04-13 22:44
Could you describe what behaviour led to this result? I'm running the latest version on mac and do not get this issue.

**Comment by ethangale25** [comment] 2022-04-14 01:09
Created my .blend file with all my objects using Blender 3.0.1.  Was utilizing BMNFTs V2.0. Created data. Began rendering batches. Decided I wanted to utilize the BMNFT V3.0 version in order to get the "begin rendering where last error occurred in batch" function, however when I uninstalled V2.0 in Add-ons, and then installed V3.0, the button didn't appear.

I am running all files off of google drive in order to have multiple computers going. Tried loading the add-on from local files and still the same error occured.

**Comment by torrinworx** [comment] 2022-04-14 02:29
Ah ok that makes sense: 

V2 and V3 NFT Data is not compatible, use this repo to convert the batch.json files to the new version: https://github.com/torrinworx/Batch_Converter

**Comment by torrinworx** [comment] 2022-04-14 02:36
I'm going to close this issue now because I'm fairly certain that that is the root cause. You can read more about the switch over in our Discord in this announcement: 
https://discord.com/channels/900195604481859634/903855375797870613/959118926690811954

**Closed by torrinworx** 2022-04-14 02:36 UTC
